name: Run dataisbeautiful bot

on:
  schedule:
    - cron: '7 6 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Debug - show requirements.txt
        run: cat requirements.txt

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Run bot
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ACCT_PASSWD: ${{ secrets.ACCT_PASSWD }}
          CATCHUP_MODE: true
        run: python app.py
